### PR TITLE
Markdownify README

### PR DESCRIPTION
**Pull request by szepeviktor**
- use headings
- unordered lists with simple dashes
- remove misleading colons
- No Imperial Grams: https://en.wikipedia.org/wiki/Kilogram#SI_multiples
- fix footer

@hendricius

### CODE REVIEW

**Comment by szepeviktor** [comment]
Soll ich es in der deutschen Version wiederholen?

**Comment by szepeviktor** [comment]
@hendricius Please consider merging this :)

**Review by hendricius — APPROVED** [review]
Thank you very much!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
