### PR TITLE
Fix video link

### PR DESCRIPTION
**Pull request by szepeviktor**
I've [left a comment](https://github.com/hendricius/pizza-dough/pull/43/files#r322052384) in the previous PR.

### CODE REVIEW

**Comment by szepeviktor** [comment]
@hendricius Friendly ping.

**Comment by szepeviktor** [comment]
@hendricius Only 1 click :)

**Comment by hendricius** [comment]
Sorry. My bad. Thank you very much!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
