### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by riofriz**
Just a little tip, never tell a person from Napoli you are using dry yeast :P
Overall good recipe tho, Fresh Brewer's yeast is the right choice.

Should look like this, give it a try, the final result will be way softer and the condiment will literally fall from your pizza when you pick up a slice.

Should look like this: 
https://www.molinomoras.it/image.php?objectType=content&imgname=e24f06087593aec0598dd64ba31708a4.jpg

### CODE REVIEW

**Comment by alireza-ahmadi** [comment]
I understand that Fresh Brewer yeast would give you better result, but it’s less widely accessible as the dry yeast. So, I suggest instead of replacing dry yeast entirely, you add a new commit and mention that "if you can’t find Fresh Brewer yeast, you can use x.xxx% dry yeast".

**Comment by alireza-ahmadi** [comment]
Also, concerning the ratio, AFAIK you should use more fresh brewer yeast if you substituting it with the dry yeast.

**Comment by alireza-ahmadi** [comment]
@riofriz Thanks 🙏

**Comment by hendricius** [comment]
Thank you very much.

For fresh active yeast you would need to use way more. I'd say probably 1% of the dough. I rather leave the dry yeast here, maybe add another line in below that you can alternate with active yeast. What do you think?

The recipe would also have to be adjusted as you would probably want to dissolve the yeast in water for it to spread evenly throughout the dough when mixing.

Me personally I have never noticed any difference in a bread with dry vs. active yeast. The only times I notice a difference is when utilising sourdough. Although I did not yet document an experiment in my [other baking repo](https://github.com/hendricius/the-bread-code) yet. I'll try to do that and post the results

**Comment by riofriz** [comment]
> The recipe would also have to be adjusted as you would probably want to dissolve the yeast in water for it to spread evenly throughout the dough when mixing.

Yeah, that's true, I gave some stuff for granted (i guess that's why I don't own a pretty good GitHub account full of recipes :P )

> Me personally I have never noticed any difference in a bread with dry vs. active yeast

As I said (looking at the doughs posted in the recipe I can tell that pizza will be already great) with brewer's yeast you'll get a way thicker result, especially leaving it growing overnight as you beautifully explained (i hate recipes where they tell you pizza can be done in few hours, is a slow and careful process). The final dough will be less fluffy and will nicely grow at high temperatures in the oven. That's what makes the crust (cornicione) that soft. The lack of condiment on the sides will allow that part to grow more, and it'll be soft rather than crunchy.

Also, active yeast makes the dough less sticky and more malleable. When you see somebody doing acrobatic pizza making, for instance, you'll notice the dough stays nicely all together, with dry yeast it would probably break after a few throws...  

Anyhow there are so many discussions around the fact that Brewer's yeast and normal yeast do exactly the same things, and I don't have enough chemical competences to actually come up with a full explanation, only thing I can say for certain is (as you probably well know) that there must be a reason why when pizza is made in Napoli is better than anywhere else in the world, even if made by people from Napoli. :)

> Although I did not yet document an experiment in my other baking repo yet. I'll try to do that and post the results

Can't wait to see what comes out of it, please keep me posted :)

**Comment by ACVis** [comment]
Pardon my ignorance, I'm a homebrewer and not much of a baker, but being a homebrewer - I've never heard of "Fresh Brewers Yeast". There's fresh yeast, and yes it's a liquid, but as far as I know there's no generic Fresh Brewers Yeast". There's hundreds of specific types of fresh yeast for brewing, just check the White Labs or Wyeast websites. Now, since I was always brewing beer, I was always looking for something specific, so I could be wrong. Or maybe "Fresh Brewer's Yeast" is what it's called at the grocery store? My ultimate question is this - if liquid yeast from White Labs or Wyeast can be used, then are there any recommendations on a specific one? 

(I unfortunately can't double check any of my statements right now since I'm at work.)

**Comment by riofriz** [comment]
@ACVis sorry that might have been me wrongly translating something from Italian.
By Fresh Brewer's yeast (Lievito di Birra fresco) I meant the actual wet cubes (is not liquid, nor dry).

Looks like [this](https://molinovigevano.com/wp-content/uploads/sites/2/2018/05/lievito-di-birra-500x500.jpeg) and you dissolve it in warm water (not hot/boiling water).

Usually, you can't store it, you buy and use it or it'll go bad. Where I am from (Salerno, in Italy) is way more common than dry yeast. 

Hope that clarifies it slightly, for what I know is called Lievito di Birra, but for my understanding is not really used to make beer. 
Funny how words throw people off sometimes ahah

**Comment by eby** [comment]
I agree with @alireza-ahmadi . I was doing similar tests and tried to find fresh yeast and was unable to within a 50 mile radius (I'm rural) except asking at an actual bakery. Both bakeries only had a sour starter they had already used the yeast in as well so it wasn't really available. I could probably find it online and have it overnighted. Every store has the dry. This is of course more US centric, I saw it all over in Europe.

Adding a list of alternative weights/ratios (fresh, sourdough, etc) would be good though.  

@ACVis Baker's yeast (which you want here) and Brewers yeast are the same species but different strains. There are probably some low alcohol brewers yeasts you could play around with here but definitely won't be the same. Probably stick with dry baker if you can't find the wet. Unfortunately it doesn't seem that wyeast or white labs do baker yeasts where you could have your local shop order it in for you.

**Comment by BurningTreeC** [comment]
here's a link I found, maybe it comes in handy

https://makebread.com.au/fresh-yeast-conversion/

**Pull request merged**
